### ISSUE TITLE
Add configuration for bar priority depending on conditions ([Suggestion] Add modifier for ap-bar)

### ISSUE THREAD

**Issue by Alucard2112** [RainmakerUA/XPMultiBar#2]
First of all, thank you for this great addon, really like it :)
As I understand it is not possible to see the ap-bar below max-level.
My suggestion here is to add a customizable modifier (like shift or something) to switch from xp to ap (maybe as long as the button is pressed or as a toggle).

**Comment by RainmakerUA** [comment]
Hi,
I've realized it just few days ago, that I haven't ever documented this feature :)
It is possible to see AP bar before you reach max. level. It is displayed when mouse is over the bar while Alt key is pressed.
I leave this issue opened and modify name to add configuration for bar priority some day :)
