### ISSUE TITLE
[KTL] doesn't appear to be working

### ISSUE THREAD

**Issue by Kiefy** [RainmakerUA/XPMultiBar#3]
Thank you for this addon!

After killing a mob which gave 86 xp, it should be showing 18, but it shows 1.

![ss](https://i.imgur.com/ZcxCw0F.png)

XPMultiBar-8.2.4c-final in WoW Classic

**Comment by RainmakerUA** [comment]
Fixed with c6d72b02772e2411a5c7fe057886e3b4eb42ae96
