### ISSUE TITLE
Request: Add another text string variable for rested levels # instead of %

### ISSUE THREAD

**Issue by raysmith59** [RainmakerUA/XPMultiBar#6]
I was looking for a way to show the number of rested levels to 2 decimals (so 1.31 instead of 131%) but didn't see one that currently existed, I figured out a way to do it in code, would you mind adding this in before your next update?  I've modified my own so it'll be fine until then.

Added to db.bars.xpstring in XPMultiBar_Main.lua:

["%[restLVL%]"] = math.floor((restedXP/nXP*100)+0.5)/100

**Comment by RainmakerUA** [comment]
Resolved by 1020154efea58511b65f3b3aad0c8cbf66cd73e5: "Add [restLVL] pattern for XP bar format) commit".
Released with version **10.1.0-final**
